<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose Month</name>
   <tag></tag>
   <elementGuidId>82479b07-1b0d-4c14-961b-518a6b91718b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'react-datepicker__month-option' and (text() = '${month}' or . = '${month}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9533ead-0c11-4241-8859-363e37bd52b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-datepicker__month-option</value>
      <webElementGuid>6fc31b2b-384a-428a-b935-c366a4def275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${month}</value>
      <webElementGuid>74808196-7c95-4691-85f4-d7a30b546c18</webElementGuid>
   </webElementProperties>
</WebElementEntity>
