<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SEARCH</name>
   <tag></tag>
   <elementGuidId>3eeef3ce-dfc9-49bc-9985-34a87776e5f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and @class = 'theme-module_btn__Dp-TQ index_sqpp-primary-download-btn__L16Sa btn btn-secondary' and (text() = 'SEARCH' or . = 'SEARCH')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.theme-module_btn__Dp-TQ.index_sqpp-primary-download-btn__L16Sa.btn.btn-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='fsSearchActions']/span/button[@type = 'button' and @class = 'theme-module_btn__Dp-TQ index_sqpp-primary-download-btn__L16Sa btn btn-secondary' and (text() = 'SEARCH' or . = 'SEARCH')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>647e28d0-c661-4760-990e-135ea763acf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b11bfd75-e9b1-4477-8a1c-c93708d5a8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_btn__Dp-TQ index_sqpp-primary-download-btn__L16Sa btn btn-secondary</value>
      <webElementGuid>43255458-a084-443c-9013-772222326006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>ffbf2f70-981c-471a-8d43-1b84c9fcc4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scflightschedule&quot;)/div[@class=&quot;FS-wrapper-container sqpp-master-container&quot;]/span[1]/div[1]/div[@class=&quot;flightSearch large-screen-size&quot;]/div[@class=&quot;flightSearchContainer&quot;]/div[@class=&quot;flightSearchFilterContainer&quot;]/div[@class=&quot;fsSearchActions&quot;]/span[@class=&quot;index_sqpp-primary-download-btn-container__FaCQe&quot;]/button[@class=&quot;theme-module_btn__Dp-TQ index_sqpp-primary-download-btn__L16Sa btn btn-secondary&quot;]</value>
      <webElementGuid>e128afe8-7aaa-4912-a5dc-ff954912cb73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>7bc10738-0a1a-4d79-b39f-481809b70fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flight-schedule[@id='scflightschedule']/div/span/div/div/div/div[2]/div[2]/span/button</value>
      <webElementGuid>0aa0a887-ff0e-4be0-a0e3-a2a46c266e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset / New Search'])[1]/preceding::button[1]</value>
      <webElementGuid>0b6cdb34-8eea-4e8b-b213-e564e1318256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need an overview for a flight or route? Download eTimetable'])[1]/preceding::button[1]</value>
      <webElementGuid>5b04a7f1-b92c-435b-b36a-978e371d8346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEARCH']/parent::*</value>
      <webElementGuid>7aaaf6c5-0172-4635-84ae-e35f7e28fdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>d90c1052-bfa2-4026-a217-c0c78769d37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>ebcd3dc2-220b-488f-bd54-8860e3601810</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
