<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Origin_destination</name>
   <tag></tag>
   <elementGuidId>56b8b4c8-79ef-4b4e-bcc9-f0f624c51099</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#destination</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='destination']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eaaf14ec-9dee-4179-8671-96cb72ab030f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2385cf1c-64be-4a40-ba16-4f1c150376e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>19771857-629a-4955-93d2-d4a4ed468351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control index_sqpp-odpair-autocomplete-input__XaMRT mx-1&quot; 
                </value>
      <webElementGuid>0e2f8b23-212d-420c-8271-b29bd0003380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Destination</value>
      <webElementGuid>df7abdf3-d2fb-4682-9edf-4571884abfd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>destination</value>
      <webElementGuid>ea8b3c23-cf97-4e9e-8689-1bf6eaec88c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>destination</value>
      <webElementGuid>6f5410ed-6f91-4945-a015-1df813a873a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;destination&quot;)</value>
      <webElementGuid>0aa86cb4-50ce-48ea-a43e-50e617c5b629</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='destination']</value>
      <webElementGuid>ead195c7-4d5e-4fa9-9544-fd1e2e1f7eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flight-schedule[@id='scflightschedule']/div/span/div/div/div/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>757e7ada-86d4-4c5e-9949-cc049568f4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>ce08d533-e86a-409a-ac21-778c509a10f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Destination' and @name = 'destination' and @id = 'destination']</value>
      <webElementGuid>a1eccdb2-0b6a-477c-808b-37184790189d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
