<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Destination_fromFlightDate</name>
   <tag></tag>
   <elementGuidId>9a6c48d2-93c5-45ee-8105-ef0cbdbe7c2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fromFlightDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fromFlightDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb1dad85-e787-4d48-8bbe-1da5e4680813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d07c9c00-a0d3-4b39-be7d-6dad4e05eec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromFlightDate</value>
      <webElementGuid>dfa46871-9922-46a2-8ddd-3da9541823cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fromFlightDate</value>
      <webElementGuid>4da7fa8e-5735-42ea-86b1-ff9538873035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c4a67616-7d03-4066-a643-56844bba156e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-date  react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>38358bd2-b675-4a6b-b588-c434575e640f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fromFlightDate&quot;)</value>
      <webElementGuid>e49b48f9-6179-4f1d-bcaa-a91e0a791899</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fromFlightDate']</value>
      <webElementGuid>55603489-dd80-4774-99f3-b3a348e02c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flight-schedule[@id='scflightschedule']/div/span/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>545c7280-7a47-4cd4-9b85-0150f7b0969e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>13dfe7f6-b12e-4712-ae81-f5c5e8dddc34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fromFlightDate' and @name = 'fromFlightDate']</value>
      <webElementGuid>97af97f2-6460-4912-bf2c-20d2763cf622</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
