<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tracking_awbInput</name>
   <tag></tag>
   <elementGuidId>07f06a2e-3c46-49e7-b797-83e66e9ae778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sqpp-tracking-quicksearch-awbfield-id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sqpp-tracking-quicksearch-awbfield-id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d511fbb-a70a-471a-a4a9-7ed9f6ce4fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sqpp-tracking-quicksearch-awbfield-id</value>
      <webElementGuid>52c1ce91-f832-4339-9fd2-50523cb310f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>78cca2b8-3771-4c30-83bc-d0008babb9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>awbInput</value>
      <webElementGuid>ef27f9e5-7c8e-4713-8bc2-9c9991d26a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter AWB number separated by a comma. For example, 618-1234XXXX.</value>
      <webElementGuid>fda36a9f-9c09-488c-9f96-1a4ed3cb8e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68036bc9-3582-4f98-be06-a9b55d70c7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o sqpp-tracking-quicksearch-awbfield form-control</value>
      <webElementGuid>f4d20cee-ea60-4287-acb6-3e987091dbb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>244ab037-76ae-46c8-8f74-376c322a4b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sqpp-tracking-quicksearch-awbfield-id&quot;)</value>
      <webElementGuid>13c5ddc7-de65-4f2f-8025-41315a22aaa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sqpp-tracking-quicksearch-awbfield-id']</value>
      <webElementGuid>a085f190-03f9-40f2-97ca-9dfa59243ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tracking-quicksearch[@id='scquicksearch']/div/div/div/div/input</value>
      <webElementGuid>b23c335a-1d7e-4677-a7ba-d0d4bdaef8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tracking-quicksearch/div/div/div/div/input</value>
      <webElementGuid>60ec2f2c-ab44-4c96-8b3f-0724cfe60c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sqpp-tracking-quicksearch-awbfield-id' and @name = 'awbInput' and @placeholder = 'Enter AWB number separated by a comma. For example, 618-1234XXXX.' and @type = 'text']</value>
      <webElementGuid>0ee2da7e-6653-4976-988d-e891b0a82686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
